name: Postprocessing and build search data

on:
  push:
    paths:
      - 'target/**'
    branches:
      - '**'

  workflow_dispatch:

jobs:
  postproc:
    uses: autohotkey-docs-translation/.github/.github/workflows/postproc.yml@master

  build-search-data:
    uses: autohotkey-docs-translation/.github/.github/workflows/build_search_data.yml@master
    needs: postproc
